### ISSUE TITLE
[ENS DApp] Rely on Status API 

### ISSUE THREAD

**Issue by jeluard** [status-im/contracts#14]
ENS DApp should rely on Status API to automatically fill necessary information.

**Comment by bgits** [comment]
This was solved in this build: https://ipfs.infura.io/ipfs/QmW2Jx22kshyoqGtNrmhU7q54ore3X9P3Gbbocr5eJ29pT/

The solution was to delay firing the post as part of DApp init sequence as it seems that the status api mounts later on.

**Comment by jeluard** [comment]
Some comments:

* permission is asked right after loading, maybe we could delay when it is strictly required?
* still need to click on `paste`, why not prefill with the proper value?

**Comment by bgits** [comment]
We could do that but was keeping it in the global store in case in needs to be used in other parts of the DApp.

The paste is if they choose to associate a different key with their address but likely there is better UX here.

**Comment by jeluard** [comment]
Could be populated by default with local status values, if any. It will be the default for vast majority of users.
They can always paste something different if needed.
