### ISSUE TITLE
[ENS DApp] Improve name validation in search screen

### ISSUE THREAD

**Issue by jeluard** [status-im/contracts#15]
On iOS it only works when validating using keyboard return. The `Done` button is not functional.

![image](https://user-images.githubusercontent.com/359723/43968459-6d7e6cea-9cc7-11e8-8885-3be459a34064.png)

**Comment by bgits** [comment]
This should be fixed now, by submitting onBlur.

**Comment by bgits** [comment]
resolved here: https://ipfs.infura.io/ipfs/QmW2Jx22kshyoqGtNrmhU7q54ore3X9P3Gbbocr5eJ29pT/
