### ISSUE TITLE
[ENS DApp] Prevent register button to be hidden by wallet address

### ISSUE THREAD

**Issue by jeluard** [status-im/contracts#17]
On some screen sizes (iPhone8) the `register` button of search screen is hidden by the wallet address.

**Comment by bgits** [comment]
Like there is overlap of the elements or you have to scroll down to see the button?

**Comment by jeluard** [comment]
![image-1](https://user-images.githubusercontent.com/359723/44031017-e46fbfc4-9f02-11e8-872a-dc923f5d3a6a.jpg)

**Comment by jeluard** [comment]
Can't scroll. Register works but it's confusing.

**Comment by bgits** [comment]
Can you post the IPFS hash your using?

**Comment by jeluard** [comment]
Using latest one: https://ipfs.infura.io/ipfs/QmW2Jx22kshyoqGtNrmhU7q54ore3X9P3Gbbocr5eJ29pT/

**Comment by bgits** [comment]
I don't have this issue on simulator iPhone 8, are you using the physical device?

Also, this was an issue on a previous version, I'm wondering if the browser might be caching because it's only showing `ipfs.infura.io` in the url?

**Comment by jeluard** [comment]
Yes on the real phone.

No status browsers will use the full URL. The address bar only drop part of URL.

**Comment by bgits** [comment]
I just tried using an iPhone SE and was not able to recreate. Is there a way for me to recreate this bug using simulator?

<img width="320" alt="png image" src="https://user-images.githubusercontent.com/4020296/44042834-52287a2e-9eef-11e8-858c-535e4ba12845.png">

**Comment by jeluard** [comment]
Can't reproduce for now.. Let's close this.
