### ISSUE TITLE
Update ENS Dapp to access Status contact public key according to new Status js API

### ISSUE THREAD

**Issue by Serhy** [status-im/contracts#18]
In the https://github.com/status-im/status-react/pull/5648 we updated Status JS API.
We need to update ENS Dapp accordingly to use new API to access contact public key (when user allow it) so it would be pre-polutated in the `Your contact code` editbox

Steps to reproduce:
1) In Status App set to Ropsten network open latest version of the ENS Dapp( https://ipfs.infura.io/ipfs/QmfPPPvFMrPbprhbUexdRKomUnSDh9NsTx2Z6fVAsHeWNb/ is the latest at 29th of August 2018)
2) On the Pop-Up asking to grand access to profile tap 'Allow'
3) Tap 'Let's Go' button
4) Search for unique ens name
5) Check whether `Your contact code` field pre-populated with the public key of your current account

TF session with video for above steps: https://app.testfairy.com/projects/4803622-status/builds/8572662/sessions/4399737300/?accessToken=j0GveCm9d6c32KjurldJu-iefHk

**Comment by bgits** [comment]
@Serhy new version with updated API deployed at: https://ipfs.infura.io/ipfs/QmYLj7gYZfKPee4BirNPBug5z41UbYf699Gy78K9M1x4pi/

**Comment by Serhy** [comment]
Works great in latest prototype https://ipfs.infura.io/ipfs/QmYLj7gYZfKPee4BirNPBug5z41UbYf699Gy78K9M1x4pi/, yes!
Thanks a lot @bgits !
