### ISSUE TITLE
Cannot have multiple execution approvals pending

### ISSUE THREAD

**Issue by cbruguera** [status-im/contracts#5]
From my understanding of this `Identity` implementation, since approval requires the _current_ nonce to be equal to the nonce the execution request was stored with, if multiple execution attempts are made (all pointing to the same nonce) after the first approval the current nonce will increase, rendering all subsequent approvals on other pending executions to fail. Am I correct? And if so, is this the desired behavior?

**Comment by 3esmit** [comment]
Thanks for the contribution.

Everytime you request an execution, the nonce increases (not line 446), even if was not approved.
To approve, you can select which nonce you want to approve.

If you have more question, feel free to open a new issue.
